# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2048M

# Mod properties
mod_version=1.4.39
maven_group=net.satisfy
archives_base_name=vinery
enabled_platforms=fabric

# Minecraft properties
minecraft_version=1.21.10

# Dependencies
cloth_fabric_version=11.1.136
fabric_loader_version=0.18.4
fabric_api_version=0.138.4+1.21.10
polymer_version=0.14.4+1.21.10
fabric_kotlin_version=1.13.8+kotlin.2.3.0